import {defineType, defineField} from 'sanity';

import {sharedQuestionFields, sharedQuestionFieldsets} from './sharedQuestionFields';

export default defineType({
    name: 'ecg',
    type: 'document',
    title: 'ECG Question',
    fieldsets: [
        ...sharedQuestionFieldsets,
        {
            name: 'general_characteristics',
            title: 'General Characteristics',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'atrial_enlargement',
            title: 'Atrial Enlargement',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'atrial_rhythms',
            title: 'Atrial Rhythms',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'junctional_rhythm',
            title: 'Junctional Rhythm',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'ventricular_rhythms',
            title: 'Ventricular Rhythms',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'conduction_abnormalities',
            title: 'AV Node Conduction Abnormalities',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'qrs_voltage_axis_abnormalities',
            title: 'QRS Voltage / Axis Abnormalities',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'ventricular_hypertrophy',
            title: 'Ventricular Hypertrophy',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'clinical_conditions',
            title: 'Clinical Conditions',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'intraventricular_conduction_abnormalities',
            title: 'Intraventricular Conduction Abnormalities',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'q_wave_myocardial_infarction_age',
            title: 'Q Wave Myocardial Infarction (Age)',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'repolarization_abnormalities',
            title: 'Repolarization Abnormalities',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'pacemakers_function',
            title: 'Pacemakers / Function',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
    ],
    fields: [
        // base fields (title, text, images, videos, etc.)
        ...sharedQuestionFields,
        defineField({
            name: 'index',
            type: 'string',
            title: 'Question Number (Index)',
            description: 'The question number (index) for this ECG question (e.g. "1", "2A", "2B", "3", etc.)',
            validation: (Rule) => Rule.required(),
        }),
        defineField({
            name: 'normal_01',
            type: 'number',
            title: 'Normal ECG',
            fieldset: 'general_characteristics',
        }),
        defineField({
            name: 'borderline_normal_normal_variant_ecg_02',
            type: 'number',
            title: 'Normal Variant ECG',
            fieldset: 'general_characteristics',
        }),
        defineField({
            name: 'incorrect_electrode_placement_03',
            type: 'number',
            title: 'Incorrect Electrode Placement',
            fieldset: 'general_characteristics',
        }),
        defineField({
            name: 'artifact_04',
            type: 'number',
            title: 'Artifact',
            fieldset: 'general_characteristics',
        }),
        defineField({
            name: 'right_atrial_enlargement_05',
            type: 'number',
            title: 'Right Atrial Abnormality / Enlargement',
            fieldset: 'atrial_enlargement',
        }),
        defineField({
            name: 'left_atrial_enlargement_06',
            type: 'number',
            title: 'Left Atrial Abnormality / Enlargement',
            fieldset: 'atrial_enlargement',
        }),
        defineField({
            name: 'sinus_rhythm_07',
            type: 'number',
            title: 'Sinus Rhythm',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'sinus_arrhythmia_08',
            type: 'number',
            title: 'Sinus Arrhythmia',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'sinus_bradycardia_09',
            type: 'number',
            title: 'Sinus Bradycardia (<60 BPM)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'sinus_tachycardia_10',
            type: 'number',
            title: 'Sinus Tachycardia (>100 BPM)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'sinus_pause_or_arrest_11',
            type: 'number',
            title: 'Sinus Pause or Arrest',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'sinoatrial_sa_exit_block_12',
            type: 'number',
            title: 'Sinoatiral (SA) Exit Block',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'atrial_premature_complexes_apc_13',
            type: 'number',
            title: 'Atrial Premature Complex(es) (APCs)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'atrial_tachycardia_14',
            type: 'number',
            title: 'Atrial Tachycardia',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'multifocal_atrial_tachycardia_mat_15',
            type: 'number',
            title: 'Multifocal Atrial Tachycardia (MAT)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'supraventricular_tachycardia_svt_16',
            type: 'number',
            title: 'Supraventricular Tachycardia (SVT)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'atrial_flutter_17',
            type: 'number',
            title: 'Atrial Flutter',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'atrial_fibrillation_18',
            type: 'number',
            title: 'Atrial Fibrillation (AFIB)',
            fieldset: 'atrial_rhythms',
        }),
        defineField({
            name: 'av_junctional_premature_complexes_jpc_19',
            type: 'number',
            title: 'AV Junctional Premature Complex(es) (JPCs)',
            fieldset: 'junctional_rhythm',
        }),
        defineField({
            name: 'av_junctional_escape_complex_es_20',
            type: 'number',
            title: 'AV Junctional Escape Complex(es)',
            fieldset: 'junctional_rhythm',
        }),
        defineField({
            name: 'av_junctional_rhythmtachycardia_21',
            type: 'number',
            title: 'AV Junctional Rhythm/Tachycardia',
            fieldset: 'junctional_rhythm',
        }),
        defineField({
            name: 'ventricular_premature_complexes_vpc_22',
            type: 'number',
            title: 'Ventricular Premature Complex(es) (VPCs)',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'ventricular_parasystole_23',
            type: 'number',
            title: 'Ventricular Parasystole',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'ventricular_tachycardia_3_successive_vpcs_vt_24',
            type: 'number',
            title: 'Ventricular Tachycardia (≥3 Successive VPCs) (VT)',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'accelerated_idioventricular_rhythm_aivr_25',
            type: 'number',
            title: 'Accelerated Idioventricular Rhythm (AIVR)',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'ventricular_escape_complexesrhythm_26',
            type: 'number',
            title: 'Ventricular Escape Complex(es) / Rhythm',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'ventricular_fibrillation_vf_27',
            type: 'number',
            title: 'Ventricular Fibrillation (VF)',
            fieldset: 'ventricular_rhythms',
        }),
        defineField({
            name: 'av_block_1_28',
            type: 'number',
            title: 'AV Block 1°',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'av_block_2_mobitz_type_i_wenckebach_29',
            type: 'number',
            title: 'AV Block, 2° - Mobitz Type I (Wenckebach)',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'av_block_2_mobitz_type_ii_30',
            type: 'number',
            title: 'AV Block, 2° - Mobitz Type II',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'av_block_2_1_31',
            type: 'number',
            title: 'AV Block, 2:1',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'av_block_3_complete_heart_block_32',
            type: 'number',
            title: 'AV Block, 3 (Complete Heart Block)',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'wolff_parkinson_white_pattern_wpw_33',
            type: 'number',
            title: 'Wolff-Parkinson-White Pattern (WPW)',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'av_dissociation_34',
            type: 'number',
            title: 'AV Dissociation',
            fieldset: 'conduction_abnormalities',
        }),
        defineField({
            name: 'low_voltage_limb_leads_35',
            type: 'number',
            title: 'Low Voltage, Limb Leads',
            fieldset: 'qrs_voltage_axis_abnormalities',
        }),
        defineField({
            name: 'low_voltage_precordial_leads_36',
            type: 'number',
            title: 'Low Voltage, Precordial Leads',
            fieldset: 'qrs_voltage_axis_abnormalities',
        }),
        defineField({
            name: 'left_axis_deviation_37',
            type: 'number',
            title: 'Left Axis Deviation (< - 30°)',
            fieldset: 'qrs_voltage_axis_abnormalities',
        }),
        defineField({
            name: 'right_axis_deviation_38',
            type: 'number',
            title: 'Right Axis Deviation (> + 100°)',
            fieldset: 'qrs_voltage_axis_abnormalities',
        }),
        defineField({
            name: 'electrical_alternans_39',
            type: 'number',
            title: 'Electrical Alternans',
            fieldset: 'qrs_voltage_axis_abnormalities',
        }),
        defineField({
            name: 'left_ventricular_hypertrophy_lvh_40',
            type: 'number',
            title: 'Left Ventricular Hypertrophy (LVH)',
            fieldset: 'ventricular_hypertrophy',
        }),
        defineField({
            name: 'right_ventricular_hypertrophy_rvh_41',
            type: 'number',
            title: 'Right Ventricular Hypertrophy (RVH)',
            fieldset: 'ventricular_hypertrophy',
        }),
        defineField({
            name: 'combined_ventricular_hypertrophy_42',
            type: 'number',
            title: 'Combined Ventricular (Biventricular) Hypertrophy',
            fieldset: 'ventricular_hypertrophy',
        }),
        defineField({
            name: 'brugada_syndrome_70',
            type: 'number',
            title: 'Brugada Syndrome',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'digitalis_toxicity_71',
            type: 'number',
            title: 'Digitalis Toxicity',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'torsades_de_pointes_72',
            type: 'number',
            title: 'Torsades de Pointes',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hyperkalemia_73',
            type: 'number',
            title: 'Hyperkalemia',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hypokalemia_74',
            type: 'number',
            title: 'Hypokalemia',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hypercalcemia_75',
            type: 'number',
            title: 'Hypercalcemia',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hypocalcemia_76',
            type: 'number',
            title: 'Hypocalcemia',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'dextrocardia_mirror_image_77',
            type: 'number',
            title: 'Dextrocardia, Mirror Image',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'acute_cor_pulmonale_pulmonary_embolus_78',
            type: 'number',
            title: 'Acute Cor Pulmonale / Pulmonary Embolus',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'pericardial_effusion_79',
            type: 'number',
            title: 'Pericardial Effusion',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'acute_pericarditis_80',
            type: 'number',
            title: 'Acute Pericarditis',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hypertrophic_cardiomyopathy_hcm_81',
            type: 'number',
            title: 'Hypertrophic Cardiomyopathy (HCM)',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'central_nervous_system_cns_disorder_82',
            type: 'number',
            title: 'Central Nervous System (CNS) Disorder',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'hypothermia_83',
            type: 'number',
            title: 'Hypothermia',
            fieldset: 'clinical_conditions',
        }),
        defineField({
            name: 'right_bundle_branch_block_complete_rbbb_43',
            type: 'number',
            title: 'Right Bundle Branch Block, Complete (RBBB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'right_bundle_branch_block_incomplete_irbbb_44',
            type: 'number',
            title: 'Right Bundle Branch Block, Incomplete (iRBBB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'left_posterior_fascicular_block_lpfb_46',
            type: 'number',
            title: 'Left Posterior Fascicular Block (LPFB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'left_anterior_fascicular_block_lafb_45',
            type: 'number',
            title: 'Left Anterior Fascicular Block (LAFB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'left_bundle_branch_block_complete_lbbb_47',
            type: 'number',
            title: 'Left Bundle Branch Block, Complete (LBBB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'left_bundle_branch_block_incomplete_ilbbb_48',
            type: 'number',
            title: 'Left Bundle Branch Block, Incomplete (iLBBB)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'aberrant_conduction_including_rate_related_49',
            type: 'number',
            title: 'Aberrant Conduction (including rate-related)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'nonspecific_iv_conduction_disturbance_50',
            type: 'number',
            title: 'Nonspecific IV Conduction Disturbance (IVCD)',
            fieldset: 'intraventricular_conduction_abnormalities',
        }),
        defineField({
            name: 'anterolateral_mi_acute_recent_51',
            type: 'number',
            title: 'Anterolateral MI (acute / recent)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'anterolateral_mi_old_indeterminate_52',
            type: 'number',
            title: 'Anterolateral MI (old / age indeterminate)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'anterior_or_anteroseptal_mi_acute_recent_53',
            type: 'number',
            title: 'Anterior or Anteroseptal MI (acute / recent)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'anterior_anteroseptal_mi_old_indeterminate_54',
            type: 'number',
            title: 'Anterior/Anteroseptal MI (old / age indeterminate)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'lateral_mi_acute_recent_55',
            type: 'number',
            title: 'Lateral MI (acute / recent)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'lateral_mi_old_indeterminate_56',
            type: 'number',
            title: 'Lateral MI (old / age indeterminate)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'inferior_mi_acute_recent_57',
            type: 'number',
            title: 'Inferior MI (acute / recent)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'inferior_mi_old_indeterminate_58',
            type: 'number',
            title: 'Inferior MI (old / age indeterminate)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'posterior_mi_acute_recent_59',
            type: 'number',
            title: 'Posterior MI (acute / recent)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'posterior_mi_old_indeterminate_60',
            type: 'number',
            title: 'Posterior MI (old / age indeterminate)',
            fieldset: 'q_wave_myocardial_infarction_age',
        }),
        defineField({
            name: 'early_repolarization_normal_variant_61',
            type: 'number',
            title: 'Early Repolarization, Normal Variant',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'juvenile_t_waves_normal_variant_62',
            type: 'number',
            title: 'Juvenile T Waves, Normal Variant',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'st_t_changes_nonspecific_63',
            type: 'number',
            title: 'Nonspecific ST-T Abnormalities',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'st_t_changes_suggesting_myocardial_ischemia_64',
            type: 'number',
            title: 'ST-T Changes suggesting Myocardial Ischemia',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'st_t_changes_suggesting_myocardial_injury_65',
            type: 'number',
            title: 'ST-T Changes suggesting Myocardial Injury',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'st_t_changes_suggesting_electrolyte_disturbance_66',
            type: 'number',
            title: 'ST-T Changes suggesting Electrolyte Disturbance',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'st_t_changes_of_hypertrophy_67',
            type: 'number',
            title: 'ST-T Changes secondary to Hypertrophy',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'prolonged_qt_interval_68',
            type: 'number',
            title: 'Prolonged QT Interval',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'prominent_u_waves_69',
            type: 'number',
            title: 'Prominent U Wave(s)',
            fieldset: 'repolarization_abnormalities',
        }),
        defineField({
            name: 'atrial_or_coronary_sinus_pacing_84',
            type: 'number',
            title: 'Atrial Pacing',
            fieldset: 'pacemakers_function',
        }),
        defineField({
            name: 'ventricular_demand_pacemaker_vvi_normal_85',
            type: 'number',
            title: 'Ventricular Demand Pacemaker (VVI), Normal',
            fieldset: 'pacemakers_function',
        }),
        defineField({
            name: 'dual_chamber_pacemaker_ddd_normal_86',
            type: 'number',
            title: 'Dual-Chamber Pacemaker (DDD), Normal',
            fieldset: 'pacemakers_function',
        }),
        defineField({
            name: 'pacemaker_malfunction_failure_to_capture_87',
            type: 'number',
            title: 'Pacemaker Malfunction, failure to capture',
            fieldset: 'pacemakers_function',
        }),
        defineField({
            name: 'pacemaker_malfunction_failure_to_sense_88',
            type: 'number',
            title: 'Pacemaker Malfunction, sensing abnormality',
            fieldset: 'pacemakers_function',
        }),
        defineField({
            name: 'biventricular_pacing_89',
            type: 'number',
            title: 'Biventricular Pacing',
            fieldset: 'pacemakers_function',
        }),
    ],
});
