import {defineType, defineField} from 'sanity';

import {sharedQuestionFields, sharedQuestionFieldsets} from './sharedQuestionFields';

export default defineType({
    title: 'Echo Question',
    name: 'echo',
    type: 'document',
    fieldsets: [
        ...sharedQuestionFieldsets,
        {
            name: 'mi_complications',
            title: 'MI Complications',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'lv_size',
            title: 'LV Size',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'lv_wall_thickness',
            title: 'LV Wall Thickness',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'lv_masses',
            title: 'LV Masses',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'lv_ejection_fraction',
            title: 'LV Ejection Fraction',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'lv_diastolic_function',
            title: 'LV Diastolic Function',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'wall_motion_abnormalities',
            title: 'Regional Wall Motion Abnormalities',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'hypokinesis',
            title: 'Hypokinesis',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'akinesis',
            title: 'Akinesis',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'thinning_scar',
            title: 'Thinning and/or Scar',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'aneurysm',
            title: 'Aneurysm',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'pseudoaneurysm',
            title: 'Pseudoaneurysm',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'ischemia',
            title: 'Ischemia (with stress echo)',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'viability',
            title: 'Viability (with stress echo)',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'adult_congenital_heart_disease',
            title: 'Adult Congenital Heart Disease',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'atrial_diseases',
            title: 'Atrial Diseases',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'cardiomyopathies',
            title: 'Cardiomyopathies',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'systemic_diseases',
            title: 'Systemic Diseases',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'aortic_valve',
            title: 'Aortic Valve',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'mitral_valve',
            title: 'Mitral Valve',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'tricuspid_valve',
            title: 'Tricuspid Valve',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'pulmonic_valve',
            title: 'Pulmonic Valve',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'prosthetic_valve',
            title: 'Prosthetic Valve',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'mild_moderate',
            title: 'Mild / Moderate',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'severe',
            title: 'Severe',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'pulmonary_disease',
            title: 'Pulmonary Disease',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'aortic_disease',
            title: 'Aortic Diseases',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'pericardial_pleural_conditions',
            title: 'Pericardial / Pleural Conditions',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
        {
            name: 'rv_function_structure_size',
            title: 'RV Function, Structure, Size',
            options: {
                collapsible: true,
                collapsed: true,
            },
        },
    ],
    fields: [
        // base fields (title, text, images, videos, etc.)
        ...sharedQuestionFields,
        defineField({
            title: 'Question Number (Index)',
            name: 'index',
            type: 'string',
            description: 'The question number (index) for this Echo question (e.g. "1", "2A", "2B", "3", etc.)',
            validation: (Rule) => Rule.required().regex(/^[0-9A-Z]+$/),
        }),
        defineField({
            title: 'Ventricular septal rupture',
            name: 'lv_vs_rupture_04',
            type: 'number',
            fieldset: 'mi_complications',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Free wall rupture',
            name: 'lv_fw_rupture_05',
            type: 'number',
            fieldset: 'mi_complications',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Ruptured papillary muscle',
            name: 'lv_ruptured_papillary_06',
            type: 'number',
            fieldset: 'mi_complications',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Small LV size',
            name: 'lv_size_small_03',
            type: 'number',
            fieldset: 'lv_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Normal LV size',
            name: 'lv_size_normal_01',
            type: 'number',
            fieldset: 'lv_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Enlarged LV size',
            name: 'lv_size_enlarged_02',
            type: 'number',
            fieldset: 'lv_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Normal LV Wall Thickness',
            name: 'lv_wall_normal_07',
            type: 'number',
            fieldset: 'lv_wall_thickness',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Concentric LVH',
            name: 'lv_concentric_increase_08',
            type: 'number',
            fieldset: 'lv_wall_thickness',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Asymmetric septal hypertrophy',
            name: 'lv_asymmetric_09',
            type: 'number',
            fieldset: 'lv_wall_thickness',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV mass or thrombus',
            name: 'lv_mass_or_thrombus_10',
            type: 'number',
            fieldset: 'lv_masses',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Metastatic tumor',
            name: 'lv_metastatic_tumor_11',
            type: 'number',
            fieldset: 'lv_masses',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Fraction: Normal to Hyperdynamic (EF >=50%)',
            name: 'lv_ejection_normal_12',
            type: 'number',
            fieldset: 'lv_ejection_fraction',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Fraction: Mild To Moderate (EF 35-49%)',
            name: 'lv_ejection_mild_13',
            type: 'number',
            fieldset: 'lv_ejection_fraction',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Fraction: Severe Reduction (EF <35%)',
            name: 'lv_ejection_severe_14',
            type: 'number',
            fieldset: 'lv_ejection_fraction',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Diastolic Function: Normal',
            name: 'lv_diastolic_normal_15',
            type: 'number',
            fieldset: 'lv_diastolic_function',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Diastolic Function: Grade 1 (abnormal)',
            name: 'lv_diastolic_grade_1_16',
            type: 'number',
            fieldset: 'lv_diastolic_function',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Diastolic Function: Grade 2 (pseudonormal)',
            name: 'lv_diastolic_grade_2_17',
            type: 'number',
            fieldset: 'lv_diastolic_function',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'LV Diastolic Function: Grade 3 (restrictive)',
            name: 'lv_diastolic_grade_3_18',
            type: 'number',
            fieldset: 'lv_diastolic_function',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Abnormal Regional LV Wall Motion',
            name: 'lv_abnormal_wall_19',
            type: 'number',
            fieldset: 'wall_motion_abnormalities',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Global LV Wall Motion Hypokinesis',
            name: 'lv_global_hypokinesis_20',
            type: 'number',
            fieldset: 'wall_motion_abnormalities',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Hypokinesis',
            name: 'apical_hypokinesis_25',
            type: 'number',
            fieldset: 'hypokinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Hypokinesis',
            name: 'septal_hypokinesis_22',
            type: 'number',
            fieldset: 'hypokinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Hypokinesis',
            name: 'lateral_hypokinesis_23',
            type: 'number',
            fieldset: 'hypokinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Hypokinesis',
            name: 'inferior_hypokinesis_24',
            type: 'number',
            fieldset: 'hypokinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Hypokinesis',
            name: 'anterior_hypokinesis_21',
            type: 'number',
            fieldset: 'hypokinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Akinesis',
            name: 'apical_akinesis_30',
            type: 'number',
            fieldset: 'akinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Akinesis',
            name: 'septal_akinesis_27',
            type: 'number',
            fieldset: 'akinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Akinesis',
            name: 'lateral_akinesis_28',
            type: 'number',
            fieldset: 'akinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Akinesis',
            name: 'inferior_akinesis_29',
            type: 'number',
            fieldset: 'akinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Akinesis',
            name: 'anterior_akinesis_26',
            type: 'number',
            fieldset: 'akinesis',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Thinning / Scar',
            name: 'apical_thinning_35',
            type: 'number',
            fieldset: 'thinning_scar',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Thinning / Scar',
            name: 'septal_thinning_32',
            type: 'number',
            fieldset: 'thinning_scar',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Thinning / Scar',
            name: 'lateral_thinning_33',
            type: 'number',
            fieldset: 'thinning_scar',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Thinning / Scar',
            name: 'inferior_thinning_34',
            type: 'number',
            fieldset: 'thinning_scar',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Thinning / Scar',
            name: 'anterior_thinning_31',
            type: 'number',
            fieldset: 'thinning_scar',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Aneurysm',
            name: 'apical_aneurysm_40',
            type: 'number',
            fieldset: 'aneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Aneurysm',
            name: 'septal_aneurysm_37',
            type: 'number',
            fieldset: 'aneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Aneurysm',
            name: 'lateral_aneurysm_38',
            type: 'number',
            fieldset: 'aneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Aneurysm',
            name: 'inferior_aneurysm_39',
            type: 'number',
            fieldset: 'aneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Aneurysm',
            name: 'anterior_aneurysm_36',
            type: 'number',
            fieldset: 'aneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Pseudoaneurysm',
            name: 'apical_pseudoaneurysm_45',
            type: 'number',
            fieldset: 'pseudoaneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Pseudoaneurysm',
            name: 'septal_pseudoaneurysm_42',
            type: 'number',
            fieldset: 'pseudoaneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Pseudoaneurysm',
            name: 'lateral_pseudoaneurysm_43',
            type: 'number',
            fieldset: 'pseudoaneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Pseudoaneurysm',
            name: 'inferior_pseudoaneurysm_44',
            type: 'number',
            fieldset: 'pseudoaneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Pseudoaneurysm',
            name: 'anterior_pseudoaneurysm_41',
            type: 'number',
            fieldset: 'pseudoaneurysm',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Ischemia',
            name: 'apical_ischemia_50',
            type: 'number',
            fieldset: 'ischemia',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Ischemia',
            name: 'septal_ischemia_47',
            type: 'number',
            fieldset: 'ischemia',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Ischemia',
            name: 'lateral_ischemia_48',
            type: 'number',
            fieldset: 'ischemia',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Ischemia',
            name: 'inferior_ischemia_49',
            type: 'number',
            fieldset: 'ischemia',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Ischemia',
            name: 'anterior_ischemia_46',
            type: 'number',
            fieldset: 'ischemia',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Viability',
            name: 'apical_viability_55',
            type: 'number',
            fieldset: 'viability',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Septal Viability',
            name: 'septal_viability_52',
            type: 'number',
            fieldset: 'viability',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lateral Wall Viability',
            name: 'lateral_viability_53',
            type: 'number',
            fieldset: 'viability',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Inferior / Posterior Wall Viability',
            name: 'inferior_viability_54',
            type: 'number',
            fieldset: 'viability',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anterior Wall Viability',
            name: 'anterior_viability_51',
            type: 'number',
            fieldset: 'viability',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Primum ASD',
            name: 'primum_asd_57',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Secundum ASD',
            name: 'secundum_asd_58',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Sinus Venosus ASD',
            name: 'sinus_asd_59',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Patent Foramen Ovale',
            name: 'patent_foramen_ovale_56',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Muscular VSD',
            name: 'muscular_vsd_60',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Membranous VSD',
            name: 'membranous_vsd_61',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Supacristal VSD',
            name: 'supacristal_vsd_62',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Patent Ductus Arteriosus',
            name: 'patent_ductus_arteriosus_63',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Subaortic Stenosus',
            name: 'subaortic_stenosus_64',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Coronary Fistula',
            name: 'coronary_fistula_65',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tetralogy of Fallot',
            name: 'tetralogy_of_fallot_66',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: "Ebstein's Anomaly",
            name: 'ebsteins_anomaly_67',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Anomalous Coronary Artery',
            name: 'anomalous_coronary_artery_148',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Complete Transposition (D-TGA)',
            name: 'complete_transposition_68',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Corrected Transposition (L-TGA)',
            name: 'corrected_transposition_69',
            type: 'number',
            fieldset: 'adult_congenital_heart_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Enlarged Left Atrium',
            name: 'enlarged_left_atrium_70',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Enlarged Right Atrium',
            name: 'enlarged_right_atrium_71',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Atrial Myxoma',
            name: 'atrial_myxoma_72',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Atrial Thrombus',
            name: 'atrial_thrombus_73',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Metastatic Tumor',
            name: 'metastatic_tumor_74',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Lipomatous Hypertrophy Of Interatrial Septum',
            name: 'atrial_hypertrophy_75',
            type: 'number',
            fieldset: 'atrial_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Nonischemic (dilated) Cardiomyopathy',
            name: 'dilated_cardiomyopathy_80',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Hypertrophic Cardiomyopathy',
            name: 'hypertrophic_cardiomyopathy_76',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Apical Hypertrophic Cardiomyopathy',
            name: 'apical_cardiomyopathy_77',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Restrictive Cardiomyopathy',
            name: 'restrictive_cardiomyopathy_78',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Takotsubo (stress induced) Cardiomyopathy',
            name: 'takotsubo_cardiomyopathy_82',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'ARVC Cardiomyopathy',
            name: 'arvd_cardiomyopathy_79',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Noncompaction Cardiomyopathy',
            name: 'noncompaction_cardiomyopathy_81',
            type: 'number',
            fieldset: 'cardiomyopathies',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Amyloid',
            name: 'amyloid_83',
            type: 'number',
            fieldset: 'systemic_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Hypereosinophilia',
            name: 'hypereosinophilia_84',
            type: 'number',
            fieldset: 'systemic_diseases',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Vegetation',
            name: 'vegetation_aortic_88',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Calcified',
            name: 'calcified_aortic_85',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Bicuspid',
            name: 'bicuspid_aortic_87',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Flail',
            name: 'flail_aortic_89',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Fibroelastoma',
            name: 'fibroelastoma_aortic_90',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Abscess',
            name: 'abscess_aortic_91',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve - Rheumatic',
            name: 'rheumatic_aortic_86',
            type: 'number',
            fieldset: 'aortic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Vegetation',
            name: 'vegetation_mitral_95',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Calcified',
            name: 'calcified_mitral_92',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Cleft',
            name: 'cleft_mitral_94',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Prolapse',
            name: 'prolapse_mitral_96',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Flail',
            name: 'flail_mitral_97',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Fibroelastoma',
            name: 'fibroelastoma_mitral_98',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Systolic Anterior Motion (SAM)',
            name: 'sam_mitral_99',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve - Rheumatic',
            name: 'rheumatic_mitral_93',
            type: 'number',
            fieldset: 'mitral_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve - Vegetation',
            name: 'vegetation_tricuspid_102',
            type: 'number',
            fieldset: 'tricuspid_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve - Fails to coapt',
            name: 'fails_tricuspid_100',
            type: 'number',
            fieldset: 'tricuspid_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve - Carcinoid',
            name: 'carcinoid_tricuspid_101',
            type: 'number',
            fieldset: 'tricuspid_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve - Prolapse',
            name: 'prolapse_tricuspid_103',
            type: 'number',
            fieldset: 'tricuspid_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve - Flail',
            name: 'flail_tricuspid_104',
            type: 'number',
            fieldset: 'tricuspid_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve - Congenitally abnormal',
            name: 'congenitally_abnormal_105',
            type: 'number',
            fieldset: 'pulmonic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve - Carcinoid',
            name: 'carcinoid_106',
            type: 'number',
            fieldset: 'pulmonic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Normal function',
            name: 'normal_prosthetic_107',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Prosthetic valve endocarditis',
            name: 'prosthetic_endocarditis_113',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Pathologic regurgitation',
            name: 'pathologic_prosthetic_108',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Perivalvular regurgitation',
            name: 'perivalvular_prosthetic_109',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Abnormally high gradient',
            name: 'elevated_prosthetic_110',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Obstruction',
            name: 'obstruction_prosthetic_111',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Prosthetic Valve - Dehiscence',
            name: 'dehiscense_prosthetic_112',
            type: 'number',
            fieldset: 'prosthetic_valve',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve Stenosis - Mild / Moderate',
            name: 'mild_mitral_stenosis_108',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve Stenosis - Mild / Moderate',
            name: 'mild_aortic_stenosis_107',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve Stenosis - Mild / Moderate',
            name: 'mild_pulmonic_stenosis_110',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve Stenosis - Mild / Moderate',
            name: 'mild_tricuspid_stenosis_109',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve Regurgitation - Mild / Moderate',
            name: 'mild_mitral_regurgitation_112',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve Regurgitation - Mild / Moderate',
            name: 'mild_aortic_regurgitation_111',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve Regurgitation - Mild / Moderate',
            name: 'mild_pulmonic_regurgitation_114',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve Regurgitation - Mild / Moderate',
            name: 'mild_tricuspid_regurgitation_113',
            type: 'number',
            fieldset: 'mild_moderate',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve Stenosis - Severe',
            name: 'severe_mitral_stenosis_116',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve Stenosis - Severe',
            name: 'severe_aortic_stenosis_115',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve Stenosis - Severe',
            name: 'severe_pulmonic_stenosis_118',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve Stenosis - Severe',
            name: 'severe_tricuspid_stenosis_117',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mitral Valve Regurgitation - Severe',
            name: 'severe_mitral_regurgitation_120',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Valve Regurgitation - Severe',
            name: 'severe_aortic_regurgitation_119',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonic Valve Regurgitation - Severe',
            name: 'severe_pulmonic_regurgitation_122',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tricuspid Valve Regurgitation - Severe',
            name: 'severe_tricuspid_regurgitation_121',
            type: 'number',
            fieldset: 'severe',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Acute Pulmonary Embolism',
            name: 'acute_pulmonary_embolism_123',
            type: 'number',
            fieldset: 'pulmonary_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pulmonary Hypertension',
            name: 'acute_pulmonary_hypertension_124',
            type: 'number',
            fieldset: 'pulmonary_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Type A dissection',
            name: 'type_a_dissection_126',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Type B dissection',
            name: 'type_b_dissection_127',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Marfan Syndrome',
            name: 'marfan_syndrome_125',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Intramural Hematoma',
            name: 'intramural_hematoma_128',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Ulcer',
            name: 'aortic_ulcer_129',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Enlargement Or Aneurysm',
            name: 'aortic_enlargement_130',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Aortic Rupture',
            name: 'aortic_rupture_131',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Sinus of Valsalva Aneurysm',
            name: 'valsalva_aneurysm_132',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Sinus of Valsalva Rupture',
            name: 'valsalva_rupture_133',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Coarctation',
            name: 'coarctation_134',
            type: 'number',
            fieldset: 'aortic_disease',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pericardial Effusion w/o tamponade',
            name: 'pericardial_effusion_135',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Tamponade',
            name: 'tamponade_136',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pericardial Mass Or Hemopericardium',
            name: 'pericardial_mass_137',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pericardial Constriction',
            name: 'pericardial_constriction_138',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pericardial Cyst',
            name: 'pericardial_cyst_139',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Pleural Effusion',
            name: 'pleural_effusion_140',
            type: 'number',
            fieldset: 'pericardial_pleural_conditions',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'RV Enlarged',
            name: 'enlarged_rv_141',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'RV Infarct',
            name: 'rv_intact_142',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Global RV Hypokinesis',
            name: 'global_hypokinesis_143',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'RV Volume Overload',
            name: 'rv_volume_overload_144',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'RV Pressure Overload',
            name: 'rv_pressure_overload_145',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Catheter or pacemaker in RV',
            name: 'catheter_pacemaker_wire_146',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
        defineField({
            title: 'Mass or thrombus in RV',
            name: 'rv_mass_thrombus_147',
            type: 'number',
            fieldset: 'rv_function_structure_size',
            validation: (Rule) => Rule.positive(),
        }),
    ],
    preview: {
        select: {
            index: 'index',
            title: 'title',
            images: 'images',
            markedImages: 'markedImages',
            videos: 'videos',
        },
        prepare(selection) {
            const {title, index, images, markedImages, videos} = selection;
            return {
                title,
                subtitle: `Media Count: ${images.length + markedImages.length + videos.length}`,
                media: () => `Echo ${index}`,
            };
        },
    },
});
