const imageProperties = [
    'question_ecg_image',
    'question_ecg_image_2',
    'question_ecg_image_3',
    'question_ecg_image_4',
    'question_ecg_image_5',
];

const markedImageProperties = [
    'question_ecg_image_marked',
    'question_ecg_image_marked_2',
    'question_ecg_image_marked_3',
    'question_ecg_image_marked_4',
    'question_ecg_image_marked_5',
];

const videoProperties = [
    'question_ecg_video',
    'question_ecg_video_2',
    'question_ecg_video_3',
    'question_ecg_video_4',
    'question_ecg_video_5',
    'question_ecg_video_6',
];

export const mediaProperties = [...imageProperties, ...markedImageProperties, ...videoProperties];

export const dict = {
    angiogram: {
        // OLD (WP) : NEW (Sanity)
        '01_normal_angiogram': 'normal_angiogram_01',
        '12_left_main_severe': 'left_main_severe_12',
        '13_left_anterior_severe': 'left_anterior_severe_13',
        '14_left_circumflex_severe': 'left_circumflex_severe_14',
        '15_right_severe': 'right_severe_15',
        '16_bypass_severe': 'bypass_severe_16',
        '07_left_main_moderate': 'left_main_moderate_07',
        '08_left_anterior_moderate': 'left_anterior_moderate_08',
        '09_left_circumflex_moderate': 'left_circumflex_moderate_09',
        '10_right_moderate': 'right_moderate_10',
        '11_bypass_moderate': 'bypass_moderate_11',
        '02_left_main_insignificant': 'left_main_insignificant_02',
        '03_left_anterior_insignificant': 'left_anterior_insignificant_03',
        '04_left_circumflex_insignificant': 'left_circumflex_insignificant_04',
        '05_right_insignificant': 'right_insignificant_05',
        '06_bypass_insignificant': 'bypass_insignificant_06',
        '17_left_main_total_occlusion': 'left_main_total_occlusion_17',
        '18_left_anterior_total_occlusion': 'left_anterior_total_occlusion_18',
        '19_left_circumflex_total_occlusion': 'left_circumflex_total_occlusion_19',
        '20_right_total_occlusion': 'right_total_occlusion_20',
        '21_bypass_total_occlusion': 'bypass_total_occlusion_21',
        '22_left_anterior_filled_collaterals': 'left_anterior_filled_collaterals_22',
        '23_left_circumflex_filled_collaterals': 'left_circumflex_filled_collaterals_23',
        '24_right_filled_collaterals': 'right_filled_collaterals_24',
        '25_bypass_filled_collaterals': 'bypass_filled_collaterals_25',
        '26_left_anterior_coronary_spasm': 'left_anterior_coronary_spasm_26',
        '27_left_circumflex_coronary_spasm': 'left_circumflex_coronary_spasm_27',
        '28_right_coronary_spasm': 'right_coronary_spasm_28',
        '29_bypass_coronary_spasm': 'bypass_coronary_spasm_29',
        '34_left_anterior_myocardial_bridge': 'left_anterior_myocardial_bridge_34',
        '35_left_circumflex_myocardial_bridge': 'left_circumflex_myocardial_bridge_35',
        '36_right_coronary_myocardial_bridge': 'right_coronary_myocardial_bridge_36',
        '37_left_main_anomalous_coronary': 'left_main_anomalous_coronary_37',
        '38_left_anterior_anomalous_coronary': 'left_anterior_anomalous_coronary_38',
        '39_left_circumflex_anomalous_coronary': 'left_circumflex_anomalous_coronary_39',
        '40_right_anomalous_coronary': 'right_anomalous_coronary_40',
        '41_left_main_coronary_fistula': 'left_main_coronary_fistula_41',
        '42_left_anterior_coronary_fistula': 'left_anterior_coronary_fistula_42',
        '43_left_circumflex_coronary_fistula': 'left_circumflex_coronary_fistula_43',
        '44_right_coronary_fistula': 'right_coronary_fistula_44',
        '30_left_anterior_coronary_thrombus': 'left_anterior_coronary_thrombus_30',
        '31_left_circumflex_coronary_thrombus': 'left_circumflex_coronary_thrombus_31',
        '32_right_coronary_thrombus': 'right_coronary_thrombus_32',
        '33_bypass_coronary_thrombus': 'bypass_coronary_thrombus_33',
        '50_left_anterior_bypass_graft': 'left_anterior_bypass_graft_50',
        '51_left_circumflex_bypass_graft': 'left_circumflex_bypass_graft_51',
        '52_right_bypass_graft': 'right_bypass_graft_52',
        '53_left_main_dissection': 'left_main_dissection_53',
        '54_left_anterior_dissection': 'left_anterior_dissection_54',
        '55_left_circumflex_dissection': 'left_circumflex_dissection_55',
        '56_right_dissection': 'right_dissection_56',
        '57_bypass_dissection': 'bypass_dissection_57',
        '45_left_main_severe_ectasia': 'left_main_severe_ectasia_45',
        '46_left_anterior_severe_ectasia': 'left_anterior_severe_ectasia_46',
        '47_left_circumflex_severe_ectasia': 'left_circumflex_severe_ectasia_47',
        '48_right_severe_ectasia': 'right_severe_ectasia_48',
        '49_bypass_severe_ectasia': 'bypass_severe_ectasia_49',
        '63_left_main_stent_occluded': 'left_main_stent_occluded_63',
        '64_left_anterior_stent_occluded': 'left_anterior_stent_occluded_64',
        '65_left_circumflex_stent_occluded': 'left_circumflex_stent_occluded_65',
        '66_right_stent_occluded': 'right_stent_occluded_66',
        '67_bypass_stent_occluded': 'bypass_stent_occluded_67',
        '58_left_main_stent_patent': 'left_main_stent_patent_58',
        '59_left_anterior_stent_patent': 'left_anterior_stent_patent_59',
        '60_left_circumflex_stent_patent': 'left_circumflex_stent_patent_60',
        '61_right_stent_patent': 'right_stent_patent_61',
        '62_bypass_stent_patent': 'bypass_stent_patent_62',
    },
    ecg: {
        // OLD (WP) : NEW (Sanity)
        '01_normal': 'normal_01',
        '02_borderline_normal_normal_variant_ecg': 'borderline_normal_normal_variant_ecg_02',
        '03_incorrect_electrode_placement': 'incorrect_electrode_placement_03',
        '04_artifact': 'artifact_04',
        '05_right_atrial_enlargement': 'right_atrial_enlargement_05',
        '06_left_atrial_enlargement': 'left_atrial_enlargement_06',
        '07_sinus_rhythm': 'sinus_rhythm_07',
        '08_sinus_arrhythmia': 'sinus_arrhythmia_08',
        '09_sinus_bradycardia': 'sinus_bradycardia_09',
        '10_sinus_tachycardia': 'sinus_tachycardia_10',
        '11_sinus_pause_or_arrest': 'sinus_pause_or_arrest_11',
        '12_sinoatrial_sa_exit_block': 'sinoatrial_sa_exit_block_12',
        '13_atrial_premature_complexes_apc': 'atrial_premature_complexes_apc_13',
        '14_atrial_tachycardia': 'atrial_tachycardia_14',
        '15_multifocal_atrial_tachycardia_mat': 'multifocal_atrial_tachycardia_mat_15',
        '16_supraventricular_tachycardia_svt': 'supraventricular_tachycardia_svt_16',
        '17_atrial_flutter': 'atrial_flutter_17',
        '18_atrial_fibrillation': 'atrial_fibrillation_18',
        '19_av_junctional_premature_complexes_jpc': 'av_junctional_premature_complexes_jpc_19',
        '20_av_junctional_escape_complex_es': 'av_junctional_escape_complex_es_20',
        '21_av_junctional_rhythmtachycardia': 'av_junctional_rhythmtachycardia_21',
        '22_ventricular_premature_complexes_vpc': 'ventricular_premature_complexes_vpc_22',
        '23_ventricular_parasystole': 'ventricular_parasystole_23',
        '24_ventricular_tachycardia_3_successive_vpcs_vt': 'ventricular_tachycardia_3_successive_vpcs_vt_24',
        '25_accelerated_idioventricular_rhythm_aivr': 'accelerated_idioventricular_rhythm_aivr_25',
        '26_ventricular_escape_complexesrhythm': 'ventricular_escape_complexesrhythm_26',
        '27_ventricular_fibrillation_vf': 'ventricular_fibrillation_vf_27',
        '28_av_block_1': 'av_block_1_28',
        '29_av_block_2_-_mobitz_type_i_wenckebach': 'av_block_2_mobitz_type_i_wenckebach_29',
        '30_av_block_2_-_mobitz_type_ii': 'av_block_2_mobitz_type_ii_30',
        '31_av_block_2-1': 'av_block_2_1_31',
        '32_av_block_3_complete_heart_block': 'av_block_3_complete_heart_block_32',
        '33_wolff-parkinson-white_pattern_wpw': 'wolff_parkinson_white_pattern_wpw_33',
        '34_av_dissociation': 'av_dissociation_34',
        '35_low_voltage_limb_leads': 'low_voltage_limb_leads_35',
        '36_low_voltage_precordial_leads': 'low_voltage_precordial_leads_36',
        '37_left_axis_deviation': 'left_axis_deviation_37',
        '38_right_axis_deviation': 'right_axis_deviation_38',
        '39_electrical_alternans': 'electrical_alternans_39',
        '40_left_ventricular_hypertrophy_lvh': 'left_ventricular_hypertrophy_lvh_40',
        '41_right_ventricular_hypertrophy_rvh': 'right_ventricular_hypertrophy_rvh_41',
        '42_combined_ventricular_hypertrophy': 'combined_ventricular_hypertrophy_42',
        '70_brugada_syndrome': 'brugada_syndrome_70',
        '71_digitalis_toxicity': 'digitalis_toxicity_71',
        '72_torsades_de_pointes': 'torsades_de_pointes_72',
        '73_hyperkalemia': 'hyperkalemia_73',
        '74_hypokalemia': 'hypokalemia_74',
        '75_hypercalcemia': 'hypercalcemia_75',
        '76_hypocalcemia': 'hypocalcemia_76',
        '77_dextrocardia_mirror_image': 'dextrocardia_mirror_image_77',
        '78_acute_cor_pulmonalepulmonary_embolus': 'acute_cor_pulmonale_pulmonary_embolus_78',
        '79_pericardial_effusion': 'pericardial_effusion_79',
        '80_acute_pericarditis': 'acute_pericarditis_80',
        '81_hypertrophic_cardiomyopathy_hcm': 'hypertrophic_cardiomyopathy_hcm_81',
        '82_central_nervous_system_cns_disorder': 'central_nervous_system_cns_disorder_82',
        '83_hypothermia': 'hypothermia_83',
        '43_right_bundle_branch_block_complete_rbbb': 'right_bundle_branch_block_complete_rbbb_43',
        '44_right_bundle_branch_block_incomplete_irbbb': 'right_bundle_branch_block_incomplete_irbbb_44',
        '46_left_posterior_fascicular_block_lpfb': 'left_posterior_fascicular_block_lpfb_46',
        '45_left_anterior_fascicular_block_lafb': 'left_anterior_fascicular_block_lafb_45',
        '47_left_bundle_branch_block_complete_lbbb': 'left_bundle_branch_block_complete_lbbb_47',
        '48_left_bundle_branch_block_incomplete_ilbbb': 'left_bundle_branch_block_incomplete_ilbbb_48',
        '49_aberrant_conduction_including_rate-related': 'aberrant_conduction_including_rate_related_49',
        '50_nonspecific_intraventricular_conduction_disturbance': 'nonspecific_iv_conduction_disturbance_50',
        '51_anterolateral_mi_acute_or_recent': 'anterolateral_mi_acute_recent_51',
        '52_anterolateral_mi_old_or_indeterminate': 'anterolateral_mi_old_indeterminate_52',
        '53_anterior_or_anteroseptal_mi_acute_or_recent': 'anterior_or_anteroseptal_mi_acute_recent_53',
        '54_anterior_or_anteroseptal_mi_old_or_indeterminate': 'anterior_anteroseptal_mi_old_indeterminate_54',
        '55_lateral_mi_acute_or_recent': 'lateral_mi_acute_recent_55',
        '56_lateral_mi_old_or_indeterminate': 'lateral_mi_old_indeterminate_56',
        '57_inferior_mi_acute_or_recent': 'inferior_mi_acute_recent_57',
        '58_inferior_mi_old_or_indeterminate': 'inferior_mi_old_indeterminate_58',
        '59_posterior_mi_acute_or_recent': 'posterior_mi_acute_recent_59',
        '60_posterior_mi_old_or_indeterminate': 'posterior_mi_old_indeterminate_60',
        '61_early_repolarization_normal_variant': 'early_repolarization_normal_variant_61',
        '62_juvenile_t_waves_normal_variant': 'juvenile_t_waves_normal_variant_62',
        '63_st-t_changes_nonspecific': 'st_t_changes_nonspecific_63',
        '64_st-t_changes_suggesting_myocardial_ischemia': 'st_t_changes_suggesting_myocardial_ischemia_64',
        '65_st-t_changes_suggesting_myocardial_injury': 'st_t_changes_suggesting_myocardial_injury_65',
        '66_st-t_changes_suggesting_electrolyte_disturbance': 'st_t_changes_suggesting_electrolyte_disturbance_66',
        '67_st-t_changes_of_hypertrophy': 'st_t_changes_of_hypertrophy_67',
        '68_prolonged_qt_interval': 'prolonged_qt_interval_68',
        '69_prominent_u_waves': 'prominent_u_waves_69',
        '84_atrial_or_coronary_sinus_pacing': 'atrial_or_coronary_sinus_pacing_84',
        '85_ventricular_demand_pacemaker_vvi_normal': 'ventricular_demand_pacemaker_vvi_normal_85',
        '86_dual-chamber_pacemaker_ddd_normal': 'dual_chamber_pacemaker_ddd_normal_86',
        '87_pacemaker_malfunction_failure_to_capture': 'pacemaker_malfunction_failure_to_capture_87',
        '88_pacemaker_malfunction_failure_to_sense': 'pacemaker_malfunction_failure_to_sense_88',
        '89_biventricular_pacing_cardiac_resynchronization_therapy': 'biventricular_pacing_89',
    },
    echo: {
        '04_lv_vs_rupture': 'lv_vs_rupture_04',
        '05_lv_fw_rupture': 'lv_fw_rupture_05',
        '06_lv_ruptured_papillary': 'lv_ruptured_papillary_06',
        '03_lv_size_small': 'lv_size_small_03',
        '01_lv_size_normal': 'lv_size_normal_01',
        '02_lv_size_enlarged': 'lv_size_enlarged_02',
        '07_lv_wall_normal': 'lv_wall_normal_07',
        '08_lv_concentric_increase': 'lv_concentric_increase_08',
        '09_lv_asymmetric': 'lv_asymmetric_09',
        '10_lv_mass_or_thrombus': 'lv_mass_or_thrombus_10',
        '11_lv_metastatic_tumor': 'lv_metastatic_tumor_11',
        '12_lv_ejection_normal': 'lv_ejection_normal_12',
        '13_lv_ejection_mild': 'lv_ejection_mild_13',
        '14_lv_ejection_severe': 'lv_ejection_severe_14',
        '15_lv_diastolic_normal': 'lv_diastolic_normal_15',
        '16_lv_diastolic_grade_1': 'lv_diastolic_grade_1_16',
        '17_lv_diastolic_grade_2': 'lv_diastolic_grade_2_17',
        '18_lv_diastolic_grade_3': 'lv_diastolic_grade_3_18',
        '19_lv_abnormal_wall': 'lv_abnormal_wall_19',
        '20_lv_global_hypokinesis': 'lv_global_hypokinesis_20',
        '25_apical_hypokinesis': 'apical_hypokinesis_25',
        '22_septal_hypokinesis': 'septal_hypokinesis_22',
        '23_lateral_hypokinesis': 'lateral_hypokinesis_23',
        '24_inferior_hypokinesis': 'inferior_hypokinesis_24',
        '21_anterior_hypokinesis': 'anterior_hypokinesis_21',
        '30_apical_akinesis': 'apical_akinesis_30',
        '27_septal_akinesis': 'septal_akinesis_27',
        '28_lateral_akinesis': 'lateral_akinesis_28',
        '29_inferior_akinesis': 'inferior_akinesis_29',
        '26_anterior_akinesis': 'anterior_akinesis_26',
        '35_apical_thinning': 'apical_thinning_35',
        '32_septal_thinning': 'septal_thinning_32',
        '33_lateral_thinning': 'lateral_thinning_33',
        '34_inferior_thinning': 'inferior_thinning_34',
        '31_anterior_thinning': 'anterior_thinning_31',
        '40_apical_aneurysm': 'apical_aneurysm_40',
        '37_septal_aneurysm': 'septal_aneurysm_37',
        '38_lateral_aneurysm': 'lateral_aneurysm_38',
        '39_inferior_aneurysm': 'inferior_aneurysm_39',
        '36_anterior_aneurysm': 'anterior_aneurysm_36',
        '45_apical_pseudoaneurysm': 'apical_pseudoaneurysm_45',
        '42_septal_pseudoaneurysm': 'septal_pseudoaneurysm_42',
        '43_lateral_pseudoaneurysm': 'lateral_pseudoaneurysm_43',
        '44_inferior_pseudoaneurysm': 'inferior_pseudoaneurysm_44',
        '41_anterior_pseudoaneurysm': 'anterior_pseudoaneurysm_41',
        '50_apical_ischemia': 'apical_ischemia_50',
        '47_septal_ischemia': 'septal_ischemia_47',
        '48_lateral_ischemia': 'lateral_ischemia_48',
        '49_inferior_ischemia': 'inferior_ischemia_49',
        '46_anterior_ischemia': 'anterior_ischemia_46',
        '55_apical_viability': 'apical_viability_55',
        '52_septal_viability': 'septal_viability_52',
        '53_lateral_viability': 'lateral_viability_53',
        '54_inferior_viability': 'inferior_viability_54',
        '51_anterior_viability': 'anterior_viability_51',
        '57_primum_asd': 'primum_asd_57',
        '58_secundum_asd': 'secundum_asd_58',
        '59_sinus_asd': 'sinus_asd_59',
        '56_patent_foramen_ovale': 'patent_foramen_ovale_56',
        '60_muscular_vsd': 'muscular_vsd_60',
        '61_membranous_vsd': 'membranous_vsd_61',
        '62_supacristal_vsd': 'supacristal_vsd_62',
        '63_patent_ductus_arteriosus': 'patent_ductus_arteriosus_63',
        '64_subaortic_stenosus': 'subaortic_stenosus_64',
        '65_coronary_fistula': 'coronary_fistula_65',
        '66_tetralogy_of_fallot': 'tetralogy_of_fallot_66',
        '67_ebsteins_anomaly': 'ebsteins_anomaly_67',
        '148_anomalous_coronary_artery': 'anomalous_coronary_artery_148',
        '68_complete_transposition': 'complete_transposition_68',
        '69_corrected_transposition': 'corrected_transposition_69',
        '70_enlarged_left_atrium': 'enlarged_left_atrium_70',
        '71_enlarged_right_atrium': 'enlarged_right_atrium_71',
        '72_atrial_myxoma': 'atrial_myxoma_72',
        '73_atrial_thrombus': 'atrial_thrombus_73',
        '74_metastatic_tumor': 'metastatic_tumor_74',
        '75_atrial_hypertrophy': 'atrial_hypertrophy_75',
        '80_dilated_cardiomyopathy': 'dilated_cardiomyopathy_80',
        '76_hypertrophic_cardiomyopathy': 'hypertrophic_cardiomyopathy_76',
        '77_apical_cardiomyopathy': 'apical_cardiomyopathy_77',
        '78_restrictive_cardiomyopathy': 'restrictive_cardiomyopathy_78',
        '82_takotsubo_cardiomyopathy': 'takotsubo_cardiomyopathy_82',
        '79_arvd_cardiomyopathy': 'arvd_cardiomyopathy_79',
        '81_noncompaction_cardiomyopathy': 'noncompaction_cardiomyopathy_81',
        '83_amyloid': 'amyloid_83',
        '84_hypereosinophilia': 'hypereosinophilia_84',
        '88_vegetation_aortic': 'vegetation_aortic_88',
        '85_calcified_aortic': 'calcified_aortic_85',
        '87_bicuspid_aortic': 'bicuspid_aortic_87',
        '89_flail_aortic': 'flail_aortic_89',
        '90_fibroelastoma_aortic': 'fibroelastoma_aortic_90',
        '91_abscess_aortic': 'abscess_aortic_91',
        '86_rheumatic_aortic': 'rheumatic_aortic_86',
        '95_vegetation_mitral': 'vegetation_mitral_95',
        '92_calcified_mitral': 'calcified_mitral_92',
        '94_cleft_mitral': 'cleft_mitral_94',
        '96_prolapse_mitral': 'prolapse_mitral_96',
        '97_flail_mitral': 'flail_mitral_97',
        '98_fibroelastoma_mitral': 'fibroelastoma_mitral_98',
        '99_sam_mitral': 'sam_mitral_99',
        '93_rheumatic_mitral': 'rheumatic_mitral_93',
        '102_vegetation_tricuspid': 'vegetation_tricuspid_102',
        '100_fails_tricuspid': 'fails_tricuspid_100',
        '101_carcinoid_tricuspid': 'carcinoid_tricuspid_101',
        '103_prolapse_tricuspid': 'prolapse_tricuspid_103',
        '104_flail_tricuspid': 'flail_tricuspid_104',
        '105_congenitally_abnormal': 'congenitally_abnormal_105',
        '106_carcinoid': 'carcinoid_106',
        '107_normal_prosthetic': 'normal_prosthetic_107',
        '113_prosthetic_endocarditis': 'prosthetic_endocarditis_113',
        '108_pathologic_prosthetic': 'pathologic_prosthetic_108',
        '109_perivalvular_prosthetic': 'perivalvular_prosthetic_109',
        '110_elevated_prosthetic': 'elevated_prosthetic_110',
        '111_obstruction_prosthetic': 'obstruction_prosthetic_111',
        '112_dehiscense_prosthetic': 'dehiscense_prosthetic_112',
        '108_mild_mitral_stenosis': 'mild_mitral_stenosis_108',
        '107_mild_aortic_stenosis': 'mild_aortic_stenosis_107',
        '110_mild_pulmonic_stenosis': 'mild_pulmonic_stenosis_110',
        '109_mild_tricuspid_stenosis': 'mild_tricuspid_stenosis_109',
        '112_mild_mitral_regurgitation': 'mild_mitral_regurgitation_112',
        '111_mild_aortic_regurgitation': 'mild_aortic_regurgitation_111',
        '114_mild_pulmonic_regurgitation': 'mild_pulmonic_regurgitation_114',
        '113_mild_tricuspid_regurgitation': 'mild_tricuspid_regurgitation_113',
        '116_severe_mitral_stenosis': 'severe_mitral_stenosis_116',
        '115_severe_aortic_stenosis': 'severe_aortic_stenosis_115',
        '118_severe_pulmonic_stenosis': 'severe_pulmonic_stenosis_118',
        '117_severe_tricuspid_stenosis': 'severe_tricuspid_stenosis_117',
        '120_severe_mitral_regurgitation': 'severe_mitral_regurgitation_120',
        '119_severe_aortic_regurgitation': 'severe_aortic_regurgitation_119',
        '122_severe_pulmonic_regurgitation': 'severe_pulmonic_regurgitation_122',
        '121_severe_tricuspid_regurgitation': 'severe_tricuspid_regurgitation_121',
        '123_acute_pulmonary_embolism': 'acute_pulmonary_embolism_123',
        '124_acute_pulmonary_hypertension': 'acute_pulmonary_hypertension_124',
        '126_type_a_dissection': 'type_a_dissection_126',
        '127_type_b_dissection': 'type_b_dissection_127',
        '125_marfan_syndrome': 'marfan_syndrome_125',
        '128_intramural_hematoma': 'intramural_hematoma_128',
        '129_aortic_ulcer': 'aortic_ulcer_129',
        '130_aortic_enlargement': 'aortic_enlargement_130',
        '131_aortic_rupture': 'aortic_rupture_131',
        '132_valsalva_aneurysm': 'valsalva_aneurysm_132',
        '133_valsalva_rupture': 'valsalva_rupture_133',
        '134_coarctation': 'coarctation_134',
        '135_pericardial_effusion': 'pericardial_effusion_135',
        '136_tamponade': 'tamponade_136',
        '137_pericardial_mass': 'pericardial_mass_137',
        '138_pericardial_constriction': 'pericardial_constriction_138',
        '139_pericardial_cyst': 'pericardial_cyst_139',
        '140_pleural_effusion': 'pleural_effusion_140',
        '141_enlarged_rv': 'enlarged_rv_141',
        '142_rv_intact': 'rv_intact_142',
        '143_global_hypokinesis': 'global_hypokinesis_143',
        '144_rv_volume_overload': 'rv_volume_overload_144',
        '145_rv_pressure_overload': 'rv_pressure_overload_145',
        '146_catheter_pacemaker_wire': 'catheter_pacemaker_wire_146',
        '147_rv_mass_thrombus': 'rv_mass_thrombus_147',
    },
};
